export const CARD_BG = [
  { id: 1, bgColor: 'linear-gradient(135deg, #e6f0f3 0%, #f7fcfa 100%)' },
  { id: 2, bgColor: 'linear-gradient(135deg, #fef9e7 0%, #fffdf4 100%)' },
  { id: 3, bgColor: 'linear-gradient(135deg, #eaf7ff 0%, #f3fbff 100%)' },
  { id: 4, bgColor: 'linear-gradient(135deg, #fff2e0 0%, #fff8f3 100%)' },
  { id: 5, bgColor: 'linear-gradient(135deg, #e7f6fe 0%, #f4fafd 100%)' },
  { id: 6, bgColor: 'linear-gradient(135deg, #f5f5f5 0%, #fbfbfb 100%)' },
  { id: 7, bgColor: 'linear-gradient(135deg, #fff4fc 0%, #fffbfc 100%)' },
  { id: 8, bgColor: 'linear-gradient(135deg, #e8fef3 0%, #f5fef8 100%)' },
  { id: 9, bgColor: 'linear-gradient(135deg, #f0ecff 0%, #f7f5ff 100%)' },
  { id: 10, bgColor: 'linear-gradient(135deg, #fef2f0 0%, #fff8f8 100%)' },
];

export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience, and specific focus areas – no generic content.",
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top – making your learning more organized.",
  },
  {
    id: "04",
    title: 'Understand the "Why" Behind Answers',
    description:
      "Beyond just answers – unlock detailed concept explanations generated by AI, helping you truly master each topic.",
  },
];


// Sample Answer Format (for reference)
export const SAMPLE_ANSWER = `\`var\`, \`let\`, and \`const\` are used to declare variables in JavaScript, but they have different scopes and behaviors.

• **\`var\`**: \`var\` has function-scoped or global scope. This means a variable declared with \`var\` inside a function is only accessible inside that function. If declared outside any function, it's a global variable.

• **\`let\`**: \`let\` has block scope. A variable declared with \`let\` is only accessible within the block (e.g., inside a \`for\` loop or an \`if\` statement) where it's defined.

\`\`\`javascript
function myFunction() {
  var x = 10; // Accessible only inside myFunction
}
console.log(x); // ReferenceError: x is not defined
var y = 20; // Accessible globally
\`\`\`

• **\`const\`**: Similar to \`let\`, \`const\` has block scope, but the value cannot be reassigned once declared. However, for objects and arrays, the contents can still be modified.

\`\`\`javascript
const arr = [1, 2, 3];
arr.push(4); // This works
arr = [5, 6]; // Error: Assignment to constant variable
\`\`\``;

// Alternative format - inline code examples (like Props vs State screenshot)
export const SAMPLE_ANSWER_INLINE = `**Props** (short for properties) are used to pass data from a parent component to a child component. They are read-only, meaning a child component cannot directly modify the props it receives; they are immutable. **State**, on the other hand, is data that is managed within a component itself. It is mutable, meaning it can be changed over time, usually in response to user actions or network requests. When \`state\` changes, React re-renders the component and its children that depend on that state.

**Props Example:** jsx // ParentComponent.js function ParentComponent() { const userName = "Alice"; return <ChildComponent name={userName} />; }

// ChildComponent.js function ChildComponent(props) { return <p>Hello, {props.name}!</p>; // props.name is "Alice" }

**State Example:** jsx import React, { useState } from 'react';

function Counter() { const [count, setCount] = useState(0); // \`count\` is the state, \`setCount\` is the updater function

return ( <div> <p>Count: {count}</p> <button onClick={() => setCount(count + 1)}>Increment</button> </div> ); }`;
